#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "adventurelog"
name = "AdventureLog"
description.en = "Travel companion for the modern-day explorer."

version = "0.11.0~ynh1"

maintainers = ["Thovi98"]

[upstream]
license = "GPL-3.0"
website = "https://adventurelog.app/"
demo = "https://demo.adventurelog.app/dashboard"
userdoc = "https://adventurelog.app/docs/usage/usage.html"
code = "https://github.com/seanmorley15/AdventureLog"
fund = "https://github.com/sponsors/seanmorley15"

[integration]
yunohost = ">= 12.1.15"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/seanmorley15/AdventureLog/archive/refs/tags/v0.11.0.tar.gz"
    sha256 = "7735efb7f44d005dcc153b53dbbe4f0251e9af825f7563f0fbd0d8d595d454e7"

    autoupdate.strategy = "latest_github_release"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    
    admin.url ="/admin"
    admin.allowed = "admins"
    admin.show_tile = false
    admin.protected = true

    [resources.ports]
    backend.default = 8015
    frontend.default = 8016

    [resources.apt]
    packages = "postgresql, postgresql-contrib, python3, python3-venv, gdal-bin, libgdal-dev, postgresql-postgis, supervisor"

    [resources.database]
    type = "postgresql"

    [resources.nodejs]
    version = "22"