#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "adventurelog"
name = "AdventureLog"
description.en = "Travel companion for the modern-day explorer."

version = "0.10.0~ynh1"

maintainers = ["Thovi98"]

[upstream]
license = "GPL-v3"
website = "https://adventurelog.app/"
demo = "https://demo.adventurelog.app/dashboard"
userdoc = "https://adventurelog.app/docs/usage/usage.html"
code = "https://github.com/seanmorley15/AdventureLog"
fund = "https://github.com/sponsors/seanmorley15"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/example"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/seanmorley15/AdventureLog/archive/refs/tags/v0.10.0.tar.gz"
    sha256 = "b2d12829098c6316c2a8eaec6ca99e553a171f3b7bc94b15159df23b6a01eb65"

    autoupdate.strategy = "latest_github_release"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    admin.url ="/admin"
    admin.allowed = "admins"
    admin.show_tile = false
    admin.protected = true

    [resources.ports]
    backend.default = 8015
    frontend.default = 8016

    [resources.apt]
    packages = "postgresql, postgresql-contrib, python3, python3-venv"

    [resources.database]
    type = "postgresql"
