#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================



source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

chown -R "$app:www-data" "$install_dir"

#=================================================
# RESTORE THE POSTGRESQL DATABASE
#=================================================
ynh_script_progression "Restoring the PostgreSQL database..."

ynh_psql_db_shell  < "./db.sql"

#=================================================
# RESTORE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_restore "/etc/systemd/system/$app-backend.service"
ynh_restore "/etc/systemd/system/$app-frontend.service"

systemctl enable "$app-backend.service" --quiet
systemctl enable "$app-frontend.service" --quiet

yunohost service add "${app}-backend" --description="AdventureLog backend service" --log="/var/log/$app/$app-backend.log"
yunohost service add "${app}-frontend" --description="AdventureLog frontend service" --log="/var/log/$app/$app-frontend.log"

ynh_restore "/etc/logrotate.d/$app"

#ynh_restore "/etc/fail2ban/jail.d/$app.conf"
#ynh_restore "/etc/fail2ban/filter.d/$app.conf"
#ynh_systemctl --action=restart --service=fail2ban

#=================================================
# RESTORE VARIOUS FILES
#=================================================

mkdir -p /var/log/$app
touch /var/log/$app/$app-backend.log
touch /var/log/$app/$app-frontend.log

ynh_restore "/var/log/$app/"
chown -R $app:$app /var/log/$app/

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's services..."

ynh_systemctl --service="${app}-backend" --action="start"
ynh_systemctl --service="${app}-frontend" --action="start"

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
