#!/usr/bin/env bash
#
# Copyright (c) 2026 YunoHost Contributors
#
# This file is part of YunoHost (see https://yunohost.org)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

export MISE_VERSION=2026.3.13

readonly MISE_INSTALL_DIR="/opt/mise-global"
export MISE_INSTALL_DIR

export MISE_GLOBAL_CONFIG_FILE="$MISE_INSTALL_DIR/config/config.toml"

export MISE_DATA_DIR="$MISE_INSTALL_DIR/binaries"
export MISE_BIN_DIR="$MISE_INSTALL_DIR/mise/bin"
export MISE_CACHE_DIR="$MISE_INSTALL_DIR/cache"

ynh_mise_install() {

    mkdir -p "${MISE_INSTALL_DIR/mise}"
    mkdir -p "${MISE_DATA_DIR}"

    if [[ ! -f "$MISE_BIN_DIR"/mise ]] || [[ "$($MISE_BIN_DIR/mise version --json | jq -r '.version' | awk '{print $1}')" != "$MISE_VERSION" ]]; then

        pushd "$MISE_INSTALL_DIR"/mise || exit
        # Install the requested version of mise
        if [[ $YNH_ARCH == "amd64" ]]; then
            ynh_hide_warnings wget https://github.com/jdx/mise/releases/download/v$MISE_VERSION/mise-v$MISE_VERSION-linux-x64.tar.xz
            tar -xf mise-v$MISE_VERSION-linux-x64.tar.xz --strip-components 1
            rm mise-v$MISE_VERSION-linux-x64.tar.xz
        elif [[ $YNH_ARCH == "arm64" ]]; then
            ynh_hide_warnings wget https://github.com/jdx/mise/releases/download/v$MISE_VERSION/mise-v$MISE_VERSION-linux-arm64.tar.xz
            tar -xf mise-v$MISE_VERSION-linux-arm64.tar.xz --strip-components 1
            rm mise-v$MISE_VERSION-linux-arm64.tar.xz
        elif [[ $YNH_ARCH == "armv7" ]]; then
            ynh_hide_warnings wget https://github.com/jdx/mise/releases/download/v$MISE_VERSION/mise-v$MISE_VERSION-linux-armv7.tar.xz
            tar -xf mise-v$MISE_VERSION-linux-armv7.tar.xz --strip-components 1
            rm mise-v$MISE_VERSION-linux-armv7.tar.xz
        else
            echo "No available mise version for this arch. Please raise an issue so we can have a look."
        fi
        popd || exit

        # Load the path of mise in $PATH
        if [[ :$PATH: != *":$MISE_BIN_DIR"* ]]; then
        PATH="$MISE_BIN_DIR:$PATH"
        fi
    fi
}